### ISSUE TITLE
badge not showing in profile view

### ISSUE THREAD

**Issue by DocDemar** [larkox/mattermost-plugin-badges#18]
It would be awesome to be able to see the badges in profile view
![2023-02-21 13 33 16](https://user-images.githubusercontent.com/6048157/220346416-f33b8f78-6c47-48d3-bbd3-50be18daede3.png)

**Comment by DocDemar** [comment]
btw thanks for an awesome plugin - we simply love it ❤️

**Comment by larkox** [comment]
The badges should be showing. I think the problem you are having is that you are using two emojis as the badge, which results in a not found emoji, and therefore, it is not showing / visible. Use only one emoji per badge and that should solve it.

**Comment by larkox** [comment]
@DocDemar Another option for this particular case (boom baby) would be to create a custom emoji that could represent that. The plugin has full support for custom emojis (even animated ones).

**Comment by DocDemar** [comment]
> @DocDemar Another option for this particular case (boom baby) would be to create a custom emoji that could represent that. The plugin has full support for custom emojis (even animated ones).

Sry - my bad - I used windows emoji shortcut (win .) to select and insert emoji - It works perfectly when using syntax :some_costum_emoji:

Thanks for this awesome plugin 👍 🥇
