### ISSUE TITLE
Handling the profile popover expand going off-screen when badges are loaded

### ISSUE THREAD

**Issue by mickmister** [larkox/mattermost-plugin-badges#4]
I have a piece of feedback on how the badges are rendered in the profile popover. It seems they are always fetched at runtime, which makes the popover expand after appearing, sometimes causing the popover to appear partially off-screen. This happens with the user attributes plugin as well, though closing and reopening the popover corrects the issue because the plugin caches the attributes, and is able to render them as soon as the popover opens the second time.

However, with the badges, nothing is cached and it will reload the badges. What do you think about including a short duration cache to allow this "second load" of the popover be corrected, as it would be with the user attributes plugin?

**Comment by larkox** [comment]
Solved at e5cce6a46453112a4e8093fcd973cce89865368d
The final solution was to reserve enough space while loading.
